---
- name: Collecting facts from ASA firewalls.
  hosts: all
  connection: network_cli
  become: yes
  become_method: enable
  vars_files:
    - ./vault/secret.yml
  tasks:
    - name: Collecing software versions.
      asa_command:
        commands:
          - show version | in ASA
      register: asa_ver
    - name: Backingup running config.
      asa_config:
        backup: yes
        save: yes
